Repository DuckDuckStudio/Chinese_git, pull requests merged in 2024-06, with the labels that each got.

#12 [feat] 新增专为开发人员打包发行版的程序
  AutoPack/AutoPack.py
  AutoPack/requirements.txt
Labels: 优化, 其他, 处理中, 新功能

#11 docs: 更新支持winget的版本
  README.md
  README_DEV.md
  USER_HANDBOOK.md
Labels: 文档

#14 末尾空行
  ABOUT_TRANSLATION.md
Labels: 优化, 文档

#15 feat: 在使用备用路线前先检测备用路线版本是否最新
  中文git.py
Labels: 优化, 处理中, 新功能
