Repository DuckDuckStudio/Chinese_git, pull requests merged in 2024-08, with the labels that each got.

#49 Merge other branch's changes
  AutoPack/AutoPack_CN.py
  ChineseGit/LICENSE
  ChineseGit/README.md
  ChineseGit/__init__.py
  ChineseGit/pyproject.toml
  ChineseGit/中文git/中文git_pypi.py
Labels: 其他, DEV-开发分支合并, 内部任务

#50 feat: 添加GitHub议题/PR模板
  .github/CODEOWNERS.md
  .github/ISSUE_TEMPLATE/BUG反馈.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/新功能请求.yml
  .github/ISSUE_TEMPLATE/新命令请求.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: 其他, 待发布, 文档, 新功能, DEV-开发分支合并, DEV-未经测试, DEV-需要注意, 内部任务, 第三方

#53 feat: 添加GitHub议题/PR模板 第2次修正
  .github/CODEOWNERS.md
  .github/ISSUE_TEMPLATE/bug_feedback.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/new_command_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: 其他, 文档, 新功能, DEV-本地测试通过, DEV-需要注意, 内部任务, DEV-PR中修复, 第三方

#54 docs: 更新贡献文档
  CONTRIBUTING.md
Labels: 文档, DEV-已完成, DEV-开发分支合并

#46 发布到Pypi的相关文件
  AutoPack/AutoPack_CN.py
  ChineseGit/LICENSE
  ChineseGit/README.md
  ChineseGit/__init__.py
  ChineseGit/pyproject.toml
  ChineseGit/中文git/中文git_pypi.py
  中文git-pypi.py
Labels: 其他, DEV-开发分支合并, DEV-未经测试, 等待补充
